#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Car-Lite Long Beach
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  Long Beach citizens who are helping create a better quality of life in our city. 
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  By leaving the car at home and choosing our feet and wheels to local trips, we are making our city safer, quieter, and cleaner--we encourage anyone else who loves the LBC to do the same.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: car-litelongbeach@gmaiul.com
org_city: Long Beach
org_state: CA

#SOCIAL MEDIA
org_twitter_username: car-litelongbeach
org_instagram_username: car-litelongbeach

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
